/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// AvailableWorkflowTriggers : The trigger rules available.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AvailableWorkflowTriggers {
    /// The list of available trigger types.
    #[serde(rename = "availableTypes")]
    pub available_types: Vec<crate::models::AvailableWorkflowTriggerTypes>,
    /// The rule key of the rule.
    #[serde(rename = "ruleKey")]
    pub rule_key: String,
}

impl AvailableWorkflowTriggers {
    /// The trigger rules available.
    pub fn new(available_types: Vec<crate::models::AvailableWorkflowTriggerTypes>, rule_key: String) -> AvailableWorkflowTriggers {
        AvailableWorkflowTriggers {
            available_types,
            rule_key,
        }
    }
}


