/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// Changelog : A log of changes made to issue fields. Changelogs related to workflow associations are currently being deprecated.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Changelog {
    #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
    pub author: Option<Box<crate::models::ChangelogAuthor>>,
    /// The date on which the change took place.
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    #[serde(rename = "historyMetadata", skip_serializing_if = "Option::is_none")]
    pub history_metadata: Option<Box<crate::models::ChangelogHistoryMetadata>>,
    /// The ID of the changelog.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The list of items changed.
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<crate::models::ChangeDetails>>,
}

impl Changelog {
    /// A log of changes made to issue fields. Changelogs related to workflow associations are currently being deprecated.
    pub fn new() -> Changelog {
        Changelog {
            author: None,
            created: None,
            history_metadata: None,
            id: None,
            items: None,
        }
    }
}


