/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// DeprecatedWorkflowScope : The scope where this workflow applies



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeprecatedWorkflowScope {
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<Box<crate::models::ScopeProject>>,
    /// The type of scope.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
}

impl DeprecatedWorkflowScope {
    /// The scope where this workflow applies
    pub fn new() -> DeprecatedWorkflowScope {
        DeprecatedWorkflowScope {
            project: None,
            r#type: None,
        }
    }
}

/// The type of scope.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "PROJECT")]
    Project,
    #[serde(rename = "TEMPLATE")]
    Template,
}

impl Default for Type {
    fn default() -> Type {
        Self::Project
    }
}

