/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// DocumentVersion : The version details of the workflow.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DocumentVersion {
    /// The version UUID.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The version number.
    #[serde(rename = "versionNumber", skip_serializing_if = "Option::is_none")]
    pub version_number: Option<i64>,
}

impl DocumentVersion {
    /// The version details of the workflow.
    pub fn new() -> DocumentVersion {
        DocumentVersion {
            id: None,
            version_number: None,
        }
    }
}


