/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// FilterSubscription : Details of a user or group subscribing to a filter.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilterSubscription {
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<Box<crate::models::FilterSubscriptionGroup>>,
    /// The ID of the filter subscription.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<crate::models::FilterSubscriptionUser>>,
}

impl FilterSubscription {
    /// Details of a user or group subscribing to a filter.
    pub fn new() -> FilterSubscription {
        FilterSubscription {
            group: None,
            id: None,
            user: None,
        }
    }
}


