/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// IssueBeanEditmeta : The metadata for the fields on the issue that can be amended.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssueBeanEditmeta {
    #[serde(rename = "fields", skip_serializing_if = "Option::is_none")]
    pub fields: Option<::std::collections::HashMap<String, crate::models::FieldMetadata>>,
}

impl IssueBeanEditmeta {
    /// The metadata for the fields on the issue that can be amended.
    pub fn new() -> IssueBeanEditmeta {
        IssueBeanEditmeta {
            fields: None,
        }
    }
}


