/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// IssueSecurityLevelMember : Issue security level member.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssueSecurityLevelMember {
    #[serde(rename = "holder")]
    pub holder: Box<crate::models::PermissionHolder>,
    /// The ID of the issue security level member.
    #[serde(rename = "id")]
    pub id: i64,
    /// The ID of the issue security level.
    #[serde(rename = "issueSecurityLevelId")]
    pub issue_security_level_id: i64,
}

impl IssueSecurityLevelMember {
    /// Issue security level member.
    pub fn new(holder: crate::models::PermissionHolder, id: i64, issue_security_level_id: i64) -> IssueSecurityLevelMember {
        IssueSecurityLevelMember {
            holder: Box::new(holder),
            id,
            issue_security_level_id,
        }
    }
}


