/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// JqlFunctionPrecomputationUpdateRequestBean : List of pairs (id and value) for precomputation updates.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct JqlFunctionPrecomputationUpdateRequestBean {
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<crate::models::JqlFunctionPrecomputationUpdateBean>>,
}

impl JqlFunctionPrecomputationUpdateRequestBean {
    /// List of pairs (id and value) for precomputation updates.
    pub fn new() -> JqlFunctionPrecomputationUpdateRequestBean {
        JqlFunctionPrecomputationUpdateRequestBean {
            values: None,
        }
    }
}


