/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LinkIssueRequestJsonBean {
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<crate::models::Comment>,
    #[serde(rename = "inwardIssue")]
    pub inward_issue: Box<crate::models::LinkedIssue>,
    #[serde(rename = "outwardIssue")]
    pub outward_issue: Box<crate::models::LinkedIssue>,
    #[serde(rename = "type")]
    pub r#type: Box<crate::models::IssueLinkType>,
}

impl LinkIssueRequestJsonBean {
    pub fn new(inward_issue: crate::models::LinkedIssue, outward_issue: crate::models::LinkedIssue, r#type: crate::models::IssueLinkType) -> LinkIssueRequestJsonBean {
        LinkIssueRequestJsonBean {
            comment: None,
            inward_issue: Box::new(inward_issue),
            outward_issue: Box::new(outward_issue),
            r#type: Box::new(r#type),
        }
    }
}


