/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// MappingsByIssueTypeOverride : Overrides, for the selected issue types, any status mappings provided in `statusMappingsByWorkflows`. Status mappings are required when the new workflow for an issue type doesn't contain all statuses that the old workflow has. Status mappings can be provided by a combination of `statusMappingsByWorkflows` and `statusMappingsByIssueTypeOverride`.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MappingsByIssueTypeOverride {
    /// The ID of the issue type for this mapping.
    #[serde(rename = "issueTypeId")]
    pub issue_type_id: String,
    /// The list of status mappings.
    #[serde(rename = "statusMappings")]
    pub status_mappings: Vec<crate::models::WorkflowAssociationStatusMapping>,
}

impl MappingsByIssueTypeOverride {
    /// Overrides, for the selected issue types, any status mappings provided in `statusMappingsByWorkflows`. Status mappings are required when the new workflow for an issue type doesn't contain all statuses that the old workflow has. Status mappings can be provided by a combination of `statusMappingsByWorkflows` and `statusMappingsByIssueTypeOverride`.
    pub fn new(issue_type_id: String, status_mappings: Vec<crate::models::WorkflowAssociationStatusMapping>) -> MappingsByIssueTypeOverride {
        MappingsByIssueTypeOverride {
            issue_type_id,
            status_mappings,
        }
    }
}


