/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// NotificationSchemeId : The ID of a notification scheme.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationSchemeId {
    /// The ID of a notification scheme.
    #[serde(rename = "id")]
    pub id: String,
}

impl NotificationSchemeId {
    /// The ID of a notification scheme.
    pub fn new(id: String) -> NotificationSchemeId {
        NotificationSchemeId {
            id,
        }
    }
}


