/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// RemoteIssueLink : Details of an issue remote link.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemoteIssueLink {
    #[serde(rename = "application", skip_serializing_if = "Option::is_none")]
    pub application: Option<crate::models::Application>,
    /// The global ID of the link, such as the ID of the item on the remote system.
    #[serde(rename = "globalId", skip_serializing_if = "Option::is_none")]
    pub global_id: Option<String>,
    /// The ID of the link.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "object", skip_serializing_if = "Option::is_none")]
    pub object: Option<crate::models::RemoteObject>,
    /// Description of the relationship between the issue and the linked item.
    #[serde(rename = "relationship", skip_serializing_if = "Option::is_none")]
    pub relationship: Option<String>,
    /// The URL of the link.
    #[serde(rename = "self", skip_serializing_if = "Option::is_none")]
    pub param_self: Option<String>,
}

impl RemoteIssueLink {
    /// Details of an issue remote link.
    pub fn new() -> RemoteIssueLink {
        RemoteIssueLink {
            application: None,
            global_id: None,
            id: None,
            object: None,
            relationship: None,
            param_self: None,
        }
    }
}


