/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// ResolutionId : The ID of an issue resolution.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResolutionId {
    /// The ID of the issue resolution.
    #[serde(rename = "id")]
    pub id: String,
}

impl ResolutionId {
    /// The ID of an issue resolution.
    pub fn new(id: String) -> ResolutionId {
        ResolutionId {
            id,
        }
    }
}


