/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// StatusCreateRequest : Details of the statuses being created and their scope.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatusCreateRequest {
    #[serde(rename = "scope")]
    pub scope: Box<crate::models::StatusScope>,
    /// Details of the statuses being created.
    #[serde(rename = "statuses")]
    pub statuses: Vec<crate::models::StatusCreate>,
}

impl StatusCreateRequest {
    /// Details of the statuses being created and their scope.
    pub fn new(scope: crate::models::StatusScope, statuses: Vec<crate::models::StatusCreate>) -> StatusCreateRequest {
        StatusCreateRequest {
            scope: Box::new(scope),
            statuses,
        }
    }
}


