/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// UiModificationContextDetails : The details of a UI modification's context, which define where to activate the UI modification.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UiModificationContextDetails {
    /// The ID of the UI modification context.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Whether a context is available. For example, when a project is deleted the context becomes unavailable.
    #[serde(rename = "isAvailable", skip_serializing_if = "Option::is_none")]
    pub is_available: Option<bool>,
    /// The issue type ID of the context.
    #[serde(rename = "issueTypeId")]
    pub issue_type_id: String,
    /// The project ID of the context.
    #[serde(rename = "projectId")]
    pub project_id: String,
    /// The view type of the context. Only `GIC`(Global Issue Create) and `IssueView` are supported.
    #[serde(rename = "viewType")]
    pub view_type: ViewType,
}

impl UiModificationContextDetails {
    /// The details of a UI modification's context, which define where to activate the UI modification.
    pub fn new(issue_type_id: String, project_id: String, view_type: ViewType) -> UiModificationContextDetails {
        UiModificationContextDetails {
            id: None,
            is_available: None,
            issue_type_id,
            project_id,
            view_type,
        }
    }
}

/// The view type of the context. Only `GIC`(Global Issue Create) and `IssueView` are supported.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ViewType {
    #[serde(rename = "GIC")]
    Gic,
    #[serde(rename = "IssueView")]
    IssueView,
}

impl Default for ViewType {
    fn default() -> ViewType {
        Self::Gic
    }
}

