/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// WorkflowTransitionRules : A workflow with transition rules.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowTransitionRules {
    /// The list of conditions within the workflow.
    #[serde(rename = "conditions", skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<crate::models::AppWorkflowTransitionRule>>,
    /// The list of post functions within the workflow.
    #[serde(rename = "postFunctions", skip_serializing_if = "Option::is_none")]
    pub post_functions: Option<Vec<crate::models::AppWorkflowTransitionRule>>,
    /// The list of validators within the workflow.
    #[serde(rename = "validators", skip_serializing_if = "Option::is_none")]
    pub validators: Option<Vec<crate::models::AppWorkflowTransitionRule>>,
    #[serde(rename = "workflowId")]
    pub workflow_id: Box<crate::models::WorkflowId>,
}

impl WorkflowTransitionRules {
    /// A workflow with transition rules.
    pub fn new(workflow_id: crate::models::WorkflowId) -> WorkflowTransitionRules {
        WorkflowTransitionRules {
            conditions: None,
            post_functions: None,
            validators: None,
            workflow_id: Box::new(workflow_id),
        }
    }
}


