/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// WorkflowCreateRequest : The create workflows payload.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowCreateRequest {
    #[serde(rename = "scope")]
    pub scope: Box<crate::models::WorkflowScope>,
    /// The statuses to associate with the workflows.
    #[serde(rename = "statuses")]
    pub statuses: Vec<crate::models::WorkflowStatusUpdate>,
    /// The details of the workflows to create.
    #[serde(rename = "workflows")]
    pub workflows: Vec<crate::models::WorkflowCreate>,
}

impl WorkflowCreateRequest {
    /// The create workflows payload.
    pub fn new(scope: crate::models::WorkflowScope, statuses: Vec<crate::models::WorkflowStatusUpdate>, workflows: Vec<crate::models::WorkflowCreate>) -> WorkflowCreateRequest {
        WorkflowCreateRequest {
            scope: Box::new(scope),
            statuses,
            workflows,
        }
    }
}


