/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// WorkflowUpdateRequest : The update workflows payload.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowUpdateRequest {
    /// The statuses to associate with the workflows.
    #[serde(rename = "statuses")]
    pub statuses: Vec<crate::models::WorkflowStatusUpdate>,
    /// The details of the workflows to update.
    #[serde(rename = "workflows")]
    pub workflows: Vec<crate::models::WorkflowUpdate>,
}

impl WorkflowUpdateRequest {
    /// The update workflows payload.
    pub fn new(statuses: Vec<crate::models::WorkflowStatusUpdate>, workflows: Vec<crate::models::WorkflowUpdate>) -> WorkflowUpdateRequest {
        WorkflowUpdateRequest {
            statuses,
            workflows,
        }
    }
}


