/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowValidationErrorList {
    /// The list of validation errors.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<crate::models::WorkflowValidationError>>,
}

impl WorkflowValidationErrorList {
    pub fn new() -> WorkflowValidationErrorList {
        WorkflowValidationErrorList {
            errors: None,
        }
    }
}


