/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowCreateValidateRequest {
    #[serde(rename = "payload")]
    pub payload: Box<crate::models::WorkflowCreateRequest>,
    #[serde(rename = "validationOptions", skip_serializing_if = "Option::is_none")]
    pub validation_options: Option<Box<crate::models::ValidationOptionsForCreate>>,
}

impl WorkflowCreateValidateRequest {
    pub fn new(payload: crate::models::WorkflowCreateRequest) -> WorkflowCreateValidateRequest {
        WorkflowCreateValidateRequest {
            payload: Box::new(payload),
            validation_options: None,
        }
    }
}


